sudo: false
language: cpp
dist: bionic
compiler: gcc

# whitelist
branches:
  only:
    - develop
    - master

script:
  - autoreconf -iv
  - mkdir build
  - ./configure --prefix=$PWD/build 
  - make CFLAGS='-g -O0 -w' CXXFLAGS='-g -O0 -w -std=c++11'
  - make install
  - make dist
  - tests/testsuite

notifications:
  email: false
