sudo: false
language: cpp

# whitelist
branches:
  only:
    - develop

matrix:
  include:
    - compiler: gcc
    # - compiler: clanggit 

script:
  - autoreconf -iv
  - ./configure 
  - make CFLAGS='-g -O0 -w' CXXFLAGS='-g -O0 -w'
  - tests/testsuite

notifications:
  email: false
