sudo: false
language: cpp

# whitelist
branches:
  only:
    - develop

matrix:
  include:
    - compiler: gcc
    # - compiler: clang

script:
  - autoreconf -iv
  - ./configure 
  - make CFLAGS='-g -O0 -w' CXXFLAGS='-g -O0 -w'
  # - make check

notifications:
  email: false
