# Site settings
title: mr Matching and Running
tag_text: mr
description: mr is a tool for NNLO Standard Model stability analysis

# Build settings
markdown: kramdown

exclude: ["README.md"]
baseurl: /mr